"""created indexes and used datatime type instead of string

Revision ID: 05070ca9f8ce
Revises: e73f4a692d84
Create Date: 2024-12-17 10:40:47.238615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05070ca9f8ce'
down_revision: Union[str, None] = 'e73f4a692d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zapis', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('zapis', 'time',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.TIME(),
               existing_nullable=False)
    op.create_index(op.f('ix_zapis_phone'), 'zapis', ['phone'], unique=False)
    op.create_index(op.f('ix_zapis_stomatology'), 'zapis', ['stomatology'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zapis_stomatology'), table_name='zapis')
    op.drop_index(op.f('ix_zapis_phone'), table_name='zapis')
    op.alter_column('zapis', 'time',
               existing_type=sa.TIME(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('zapis', 'date',
               existing_type=sa.DATE(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
