"""added creted_at column

Revision ID: 079f97bbbe27
Revises: f719b7be13fc
Create Date: 2024-12-17 11:35:09.689645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079f97bbbe27'
down_revision: Union[str, None] = 'f719b7be13fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zapis', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zapis', 'created_at')
    # ### end Alembic commands ###
