"""Initial migrations

Revision ID: 0b8bd592d1e7
Revises: 
Create Date: 2024-12-13 12:57:42.462944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b8bd592d1e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stomatology',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('zapis',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('stomatology', sa.String(), nullable=False),
    sa.Column('zapis_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phone', 'date')
    )
    op.add_column('logs', sa.Column('stomatology', sa.VARCHAR(length=30), nullable=False))
    op.add_column('logs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('logs', 'request_url',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('logs', 'response_body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_stomatology'), 'logs', ['stomatology'], unique=False)
    op.drop_column('logs', 'time')
    op.drop_column('logs', 'response_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('response_status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('logs', sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_logs_stomatology'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.alter_column('logs', 'response_body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('logs', 'request_method',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('logs', 'request_url',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('logs', 'id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('logs', 'is_active')
    op.drop_column('logs', 'stomatology')
    op.drop_table('zapis')
    op.drop_table('stomatology')
    # ### end Alembic commands ###
