"""created indexes and used datatime type instead of string

Revision ID: 265288c34891
Revises: 05070ca9f8ce
Create Date: 2024-12-17 10:42:59.169763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265288c34891'
down_revision: Union[str, None] = '05070ca9f8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stomatology', sa.VARCHAR(length=30), nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), nullable=False),
    sa.Column('method', sa.VARCHAR(length=6), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_stomatology'), 'logs', ['stomatology'], unique=False)
    op.create_table('zapis',
    sa.Column('stomatology', sa.String(), nullable=False),
    sa.Column('zapis_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=19), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('zhaloba', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('zapis_id')
    )
    op.create_index(op.f('ix_zapis_phone'), 'zapis', ['phone'], unique=False)
    op.create_index(op.f('ix_zapis_stomatology'), 'zapis', ['stomatology'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zapis_stomatology'), table_name='zapis')
    op.drop_index(op.f('ix_zapis_phone'), table_name='zapis')
    op.drop_table('zapis')
    op.drop_index(op.f('ix_logs_stomatology'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
