"""added iin

Revision ID: 4ad045253d45
Revises: 44dddc4cca37
Create Date: 2024-12-23 10:54:27.477907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad045253d45'
down_revision: Union[str, None] = '44dddc4cca37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zapis', sa.Column('iin', sa.VARCHAR(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zapis', 'iin')
    # ### end Alembic commands ###
