"""set nullable to true for empty strings

Revision ID: 577c6f304dbd
Revises: deb0ae4e3c61
Create Date: 2024-12-20 12:08:47.085803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577c6f304dbd'
down_revision: Union[str, None] = 'deb0ae4e3c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zapis', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('zapis', 'zhaloba',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zapis', 'zhaloba',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zapis', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
