"""Initial migrations

Revision ID: 6457365a79c9
Revises: 0b8bd592d1e7
Create Date: 2024-12-13 13:07:57.477376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6457365a79c9'
down_revision: Union[str, None] = '0b8bd592d1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('stomatology', sa.VARCHAR(length=30), nullable=False),
    sa.Column('request_url', sa.VARCHAR(length=40), nullable=False),
    sa.Column('request_method', sa.VARCHAR(length=6), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_stomatology'), 'logs', ['stomatology'], unique=False)
    op.create_table('stomatology',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('zapis',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('stomatology', sa.String(), nullable=False),
    sa.Column('zapis_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phone', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zapis')
    op.drop_table('stomatology')
    op.drop_index(op.f('ix_logs_stomatology'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
