"""updated deprecated model fields

Revision ID: 7eb6adde726b
Revises: c17dfba1b985
Create Date: 2024-12-13 16:26:04.195485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb6adde726b'
down_revision: Union[str, None] = 'c17dfba1b985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'url',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
