"""added nullable to request body on logs

Revision ID: b9e16c18fed8
Revises: 7eb6adde726b
Create Date: 2024-12-13 16:30:24.839567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e16c18fed8'
down_revision: Union[str, None] = '7eb6adde726b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'request_body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'request_body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
