"""added time to logs

Revision ID: c03a6b73dbff
Revises: fc45b6fdcc60
Create Date: 2024-12-23 12:29:09.538778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03a6b73dbff'
down_revision: Union[str, None] = 'fc45b6fdcc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('time', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'time')
    # ### end Alembic commands ###
