"""sqladmin boolean related problem

Revision ID: deb0ae4e3c61
Revises: dfe6ed076d23
Create Date: 2024-12-19 11:06:19.632556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb0ae4e3c61'
down_revision: Union[str, None] = 'dfe6ed076d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
