"""sqladmin boolean related problem

Revision ID: dfe6ed076d23
Revises: 079f97bbbe27
Create Date: 2024-12-19 10:22:30.183854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe6ed076d23'
down_revision: Union[str, None] = '079f97bbbe27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
