"""made zapis table to store full info

Revision ID: e73f4a692d84
Revises: b9e16c18fed8
Create Date: 2024-12-16 20:24:02.420909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73f4a692d84'
down_revision: Union[str, None] = 'b9e16c18fed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zapis', sa.Column('time', sa.VARCHAR(length=5), nullable=False))
    op.add_column('zapis', sa.Column('doctor_id', sa.INTEGER(), nullable=False))
    op.add_column('zapis', sa.Column('patient_name', sa.String(), nullable=False))
    op.add_column('zapis', sa.Column('comment', sa.String(), nullable=False))
    op.add_column('zapis', sa.Column('zhaloba', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zapis', 'zhaloba')
    op.drop_column('zapis', 'comment')
    op.drop_column('zapis', 'patient_name')
    op.drop_column('zapis', 'doctor_id')
    op.drop_column('zapis', 'time')
    # ### end Alembic commands ###
