"""Initial migrations

Revision ID: e9e5aa12f1c6
Revises: 6457365a79c9
Create Date: 2024-12-13 13:31:13.765608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e5aa12f1c6'
down_revision: Union[str, None] = '6457365a79c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('url', sa.VARCHAR(length=40), nullable=False))
    op.add_column('logs', sa.Column('method', sa.VARCHAR(length=6), nullable=False))
    op.add_column('logs', sa.Column('status_code', sa.Integer(), nullable=False))
    op.drop_column('logs', 'request_method')
    op.drop_column('logs', 'is_active')
    op.drop_column('logs', 'request_url')
    op.add_column('zapis', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zapis', 'is_active')
    op.add_column('logs', sa.Column('request_url', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('logs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('logs', sa.Column('request_method', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('logs', 'status_code')
    op.drop_column('logs', 'method')
    op.drop_column('logs', 'url')
    # ### end Alembic commands ###
