"""added iin

Revision ID: fc45b6fdcc60
Revises: 4ad045253d45
Create Date: 2024-12-23 10:57:28.230428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc45b6fdcc60'
down_revision: Union[str, None] = '4ad045253d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zapis', sa.Column('iin', sa.VARCHAR(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zapis', 'iin')
    # ### end Alembic commands ###
